// fakeReports.js
export const fakeReports = [
  {
    id: "r1",
    userId: "u201",
    userName: "Amit Kumar",
    type: "tsunami",
    severity: "critical",
    description: "Tsunami alert issued near Chennai coastline.",
    location: {
      lat: 13.0827,
      lng: 80.2707,
      address: "Marina Beach, Chennai, Tamil Nadu, India",
    },
    timestamp: new Date().toISOString(),
    media: ["https://picsum.photos/300/200?random=1"],
    verified: false,
    likes: 15,
    comments: 5,
  },
  {
    id: "r2",
    userId: "u202",
    userName: "Neha Singh",
    type: "flooding",
    severity: "high",
    description: "Heavy flooding reported in Patna due to Ganga river overflow.",
    location: {
      lat: 25.5941,
      lng: 85.1376,
      address: "Patna, Bihar, India",
    },
    timestamp: new Date().toISOString(),
    media: [],
    verified: true,
    likes: 22,
    comments: 7,
  },
  {
    id: "r3",
    userId: "u203",
    userName: "Rohit Sharma",
    type: "storm_surge",
    severity: "medium",
    description: "Storm surge warnings along Gujarat coast.",
    location: {
      lat: 22.3072,
      lng: 73.1812,
      address: "Vadodara, Gujarat, India",
    },
    timestamp: new Date().toISOString(),
    media: ["https://picsum.photos/300/200?random=2"],
    verified: false,
    likes: 12,
    comments: 3,
  },
  {
    id: "r4",
    userId: "u204",
    userName: "Priya Das",
    type: "high_waves",
    severity: "low",
    description: "High waves reported at Goa beaches, tourists advised caution.",
    location: {
      lat: 15.4909,
      lng: 73.8278,
      address: "Panaji, Goa, India",
    },
    timestamp: new Date().toISOString(),
    media: [],
    verified: true,
    likes: 10,
    comments: 2,
  },
  {
    id: "r5",
    userId: "u205",
    userName: "Anil Verma",
    type: "coastal_current",
    severity: "high",
    description: "Strong coastal currents observed in Visakhapatnam.",
    location: {
      lat: 17.6868,
      lng: 83.2185,
      address: "Visakhapatnam, Andhra Pradesh, India",
    },
    timestamp: new Date().toISOString(),
    media: ["https://picsum.photos/300/200?random=3"],
    verified: false,
    likes: 18,
    comments: 4,
  },
];
