"""Label keywords for disaster classification."""

LABEL_KEYWORDS = {
    'tsunami': 'tsunami, tidal wave, sea wave, giant wave, water surge',
    'cyclone': 'cyclone, hurricane, typhoon, storm, tropical storm, severe storm, depression',
    'flooding': 'flood, flash flood, river overflow, waterlogging, inundated, submerged, heavy flooding',
    'storm_surge': 'storm surge, sea surge, seawater intrusion, coastal flooding, waves crashing',
    'earthquake': 'earthquake, tremor, seismic activity, aftershock, quake, magnitude',
    'landslide': 'landslide, mudslide, hill collapse, slope failure, debris flow, rockslide',
    'erosion': 'coastal erosion, beach erosion, shore erosion, sand loss',
    'heavy_rain': 'heavy rain, rainfall, downpour, monsoon rain, cloudburst, torrential rain',
    'wind': 'strong winds, high winds, gusts, gale, windstorm, stormy winds',
    'low_pressure': 'low pressure, depression formed, cyclonic circulation, pressure drop',
    'ocean_conditions': 'rough sea, high tide, tidal surge, rip current, ocean swell, big waves',
    'casualties': 'dead, deaths, fatalities, injured, wounded, casualties, missing, disappeared',
    'trapped_people': 'trapped, stranded, stuck, cut off, isolated, cannot escape',
    'property_damage': 'destroyed house, collapsed building, broken infrastructure, damaged road, washed away',
    'infrastructure': 'power cut, blackout, communication down, network outage, bridge collapse, transport disrupted',
    'livelihood': 'fishermen stranded, boats damaged, crops destroyed, lost nets, destroyed fields',
    'alerts': 'alert, warning, siren, red alert, yellow alert, advisory, issued notice',
    'evacuation': 'evacuation, evacuate, moved to shelter, taken to safety, relocation',
    'rescue': 'rescue, saved, rescued, NDRF, SDRF, coast guard, navy rescue, emergency services',
    'relief_camps': 'relief camp, shelter, safe place, distribution point, food camp, water supply',
    'aid': 'relief supplies, aid distribution, food packets, drinking water, clothes, medical help, donation, volunteers',
    'distress_signals': 'help, SOS, need food, need water, need medicine, please rescue, urgent help',
    'damage_reports': 'flooded street, road blocked, house collapsed, wall fell, water entered home',
    'social_sentiment': 'prayers, stay safe, tragic, disaster struck, heartbreaking, solidarity',
    'authorities': 'government alert, official update, disaster management, INCOIS, IMD, meteorological department, coast guard',
    'coordination': 'emergency response, command center, disaster relief, coordination team',
    'media_reports': 'breaking news, urgent news, news alert, media coverage, live report',
    'coastal_terms': 'coast, beach, shore, seaside, bay, port, harbor, jetty, island, delta',
    'community_terms': 'village, fishermen, coastal town, hamlet, community center, colony',
    'epidemics': 'disease outbreak, cholera, dengue, malaria, fever spreading after flood',
    'contamination': 'contaminated water, dirty water, unsafe drinking water, sewage, pollution',
    'food_shortage': 'food shortage, no supplies, ration finished, hunger, starving',
    'economic_loss': 'property loss, crop loss, livelihood loss, financial damage, destroyed market'
}
